import 'reflect-metadata';
import { S3Service } from '../../core/aws/s3/s3Service';
import { UserService } from '../../modules/user/userService';
import { OpenAIService } from '../../core/open_ai/openaiService';
import { EmbeddingsService } from '../../core/embeddings/embeddingsService';
import { PineconeService } from '../../core/pinecone/pineconeService';
import { SiglipService } from '../../core/siglip/siglipService';
import { ExploreRequestService } from '../../modules/explore/exploreRequestService';
import { ProductPreferenceService } from '../../modules/explore/productPreferencesService';
import { ProductSearchService } from '../../modules/product/productSearchService';
import { ProductService } from '../../modules/product/productService';
import { ExploreService } from '../../modules/explore/exploreService';
import { CartService } from '../../modules/cart/cartService';
import { AnthropicService } from '../../core/anthropic/anthropicService';
import { BillingService } from '../../modules/billing/billingService';
import { CohereService } from '../../core/cohere/cohereService';
import { VoyageService } from '../../core/voyage/voyageService';
import { SparseService } from '../../core/sparse/sparseService';
import { OrderManagementService } from '../../modules/orderManagement/orderManagementsService';
import { NotificationsService } from '../../modules/notifications/notificationsService';
import { SlackService } from '../../modules/slack/slackService';
import { MockService } from '../../modules/mock/mockService';
import { EmailService } from '../../core/email/emailService';
import { RedisService } from '../../core/redis/redisService';
import { ProductScraperService } from '../../modules/productScraper/productScraperService';
import { AdminService } from '../../modules/admin/adminService';
import { SupabaseStorageService } from '../../core/supabase/supabaseStorageService';
import { PinterestService } from '../../modules/pinterest/pinterestService';
import { ImagePreferenceService } from '../../modules/explore/imagePreferencesService';
import { ImageDownloaderService } from '../../core/imageDownloader/imageDownloaderService';
import { ProductImageService } from '../../core/productImage/productImageService';
import { Perf } from '../../core/performance/performance';
import { ShipmentTrackingService } from '../../modules/shipping/shipmentTrackingService';
import { BrexService } from '../../core/brex/brexService';
import { ShippingEmailService } from '../../modules/shipping/shippingEmailService';
import { getService } from './base';
import { OrderAutomationService } from '../../modules/orderAutomation/orderAutomationService';
import { GroqService } from '../../core/groq/groqService';
import { CommentingService } from '../../modules/commenting/commentingService';
import { StylePickerProductService } from '../../modules/product/stylePickerProductService';
import { DiscoveryService } from '../../modules/discovery/discoveryService';

// Services
export const s3Service = getService(S3Service);
export const supabaseStorageService = getService(SupabaseStorageService);
export const userService = getService(UserService);
export const openAIService = getService(OpenAIService);
export const siglipService = getService(SiglipService);
export const embeddingsService = getService(EmbeddingsService);
export const pineconeService = getService(PineconeService);
export const exploreRequestService = getService(ExploreRequestService);
export const productPreferenceService = getService(ProductPreferenceService);
export const productService = getService(ProductService);
export const productSearchService = getService(ProductSearchService);
export const exploreService = getService(ExploreService);
export const cartService = getService(CartService);
export const anthropicService = getService(AnthropicService);
export const billingService = getService(BillingService);
export const cohereService = getService(CohereService);
export const voyageService = getService(VoyageService);
export const sparseService = getService(SparseService);
export const orderManagementService = getService(OrderManagementService);
export const notificationsService = getService(NotificationsService);
export const slackService = getService(SlackService);
export const mockService = getService(MockService);
export const discoveryService = getService(DiscoveryService);
export const emailService = getService(EmailService);
export const redisService = getService(RedisService);
export const productScraperService = getService(ProductScraperService);
export const adminService = getService(AdminService);
export const pinterestService = getService(PinterestService);
export const imagePreferenceService = getService(ImagePreferenceService);
export const imageDownloaderService = getService(ImageDownloaderService);
export const productImageService = getService(ProductImageService);
export const shipmentTrackingService = getService(ShipmentTrackingService);
export const shippingEmailService = getService(ShippingEmailService);
// export const ddTraceService = getService(DDTraceService);
export const perf = getService(Perf);
export const brexService = getService(BrexService);
export const orderAutomationService = getService(OrderAutomationService);
export const groqService = getService(GroqService);
export const commentingService = getService(CommentingService);
export const stylePickerProductService = getService(StylePickerProductService);
