// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v5.29.3
// source: core/core.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "core";

export enum EmbeddingModel {
  EMBEDDING_MODEL_SIGLIP = 0,
  EMBEDDING_MODEL_TEXT_EMBEDDING_3_LARGE = 1,
  EMBEDDING_MODEL_VOYAGE_LARGE_3 = 2,
  EMBEDDING_MODEL_VOYAGE_LARGE_3_MULTIMODAL = 3,
  UNRECOGNIZED = -1,
}

export function embeddingModelFromJSON(object: any): EmbeddingModel {
  switch (object) {
    case 0:
    case "EMBEDDING_MODEL_SIGLIP":
      return EmbeddingModel.EMBEDDING_MODEL_SIGLIP;
    case 1:
    case "EMBEDDING_MODEL_TEXT_EMBEDDING_3_LARGE":
      return EmbeddingModel.EMBEDDING_MODEL_TEXT_EMBEDDING_3_LARGE;
    case 2:
    case "EMBEDDING_MODEL_VOYAGE_LARGE_3":
      return EmbeddingModel.EMBEDDING_MODEL_VOYAGE_LARGE_3;
    case 3:
    case "EMBEDDING_MODEL_VOYAGE_LARGE_3_MULTIMODAL":
      return EmbeddingModel.EMBEDDING_MODEL_VOYAGE_LARGE_3_MULTIMODAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EmbeddingModel.UNRECOGNIZED;
  }
}

export function embeddingModelToJSON(object: EmbeddingModel): string {
  switch (object) {
    case EmbeddingModel.EMBEDDING_MODEL_SIGLIP:
      return "EMBEDDING_MODEL_SIGLIP";
    case EmbeddingModel.EMBEDDING_MODEL_TEXT_EMBEDDING_3_LARGE:
      return "EMBEDDING_MODEL_TEXT_EMBEDDING_3_LARGE";
    case EmbeddingModel.EMBEDDING_MODEL_VOYAGE_LARGE_3:
      return "EMBEDDING_MODEL_VOYAGE_LARGE_3";
    case EmbeddingModel.EMBEDDING_MODEL_VOYAGE_LARGE_3_MULTIMODAL:
      return "EMBEDDING_MODEL_VOYAGE_LARGE_3_MULTIMODAL";
    case EmbeddingModel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum VoyageEmbeddingModel {
  VOYAGE_LARGE_3 = 0,
  UNRECOGNIZED = -1,
}

export function voyageEmbeddingModelFromJSON(object: any): VoyageEmbeddingModel {
  switch (object) {
    case 0:
    case "VOYAGE_LARGE_3":
      return VoyageEmbeddingModel.VOYAGE_LARGE_3;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VoyageEmbeddingModel.UNRECOGNIZED;
  }
}

export function voyageEmbeddingModelToJSON(object: VoyageEmbeddingModel): string {
  switch (object) {
    case VoyageEmbeddingModel.VOYAGE_LARGE_3:
      return "VOYAGE_LARGE_3";
    case VoyageEmbeddingModel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OpenAIEmbeddingModel {
  TEXT_EMBEDDING_3_LARGE = 0,
  UNRECOGNIZED = -1,
}

export function openAIEmbeddingModelFromJSON(object: any): OpenAIEmbeddingModel {
  switch (object) {
    case 0:
    case "TEXT_EMBEDDING_3_LARGE":
      return OpenAIEmbeddingModel.TEXT_EMBEDDING_3_LARGE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OpenAIEmbeddingModel.UNRECOGNIZED;
  }
}

export function openAIEmbeddingModelToJSON(object: OpenAIEmbeddingModel): string {
  switch (object) {
    case OpenAIEmbeddingModel.TEXT_EMBEDDING_3_LARGE:
      return "TEXT_EMBEDDING_3_LARGE";
    case OpenAIEmbeddingModel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum LLMProvider {
  LLM_PROVIDER_OPENAI = 0,
  LLM_PROVIDER_ANTHROPIC = 1,
  UNRECOGNIZED = -1,
}

export function lLMProviderFromJSON(object: any): LLMProvider {
  switch (object) {
    case 0:
    case "LLM_PROVIDER_OPENAI":
      return LLMProvider.LLM_PROVIDER_OPENAI;
    case 1:
    case "LLM_PROVIDER_ANTHROPIC":
      return LLMProvider.LLM_PROVIDER_ANTHROPIC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return LLMProvider.UNRECOGNIZED;
  }
}

export function lLMProviderToJSON(object: LLMProvider): string {
  switch (object) {
    case LLMProvider.LLM_PROVIDER_OPENAI:
      return "LLM_PROVIDER_OPENAI";
    case LLMProvider.LLM_PROVIDER_ANTHROPIC:
      return "LLM_PROVIDER_ANTHROPIC";
    case LLMProvider.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AnthropicModel {
  CLAUDE_3_5_SONNET_LATEST = 0,
  CLAUDE_3_7_SONNET_LATEST = 1,
  UNRECOGNIZED = -1,
}

export function anthropicModelFromJSON(object: any): AnthropicModel {
  switch (object) {
    case 0:
    case "CLAUDE_3_5_SONNET_LATEST":
      return AnthropicModel.CLAUDE_3_5_SONNET_LATEST;
    case 1:
    case "CLAUDE_3_7_SONNET_LATEST":
      return AnthropicModel.CLAUDE_3_7_SONNET_LATEST;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AnthropicModel.UNRECOGNIZED;
  }
}

export function anthropicModelToJSON(object: AnthropicModel): string {
  switch (object) {
    case AnthropicModel.CLAUDE_3_5_SONNET_LATEST:
      return "CLAUDE_3_5_SONNET_LATEST";
    case AnthropicModel.CLAUDE_3_7_SONNET_LATEST:
      return "CLAUDE_3_7_SONNET_LATEST";
    case AnthropicModel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OpenAIModel {
  GPT_4O = 0,
  GPT_3_5_TURBO = 1,
  O1_MINI = 2,
  O1_PREVIEW = 3,
  O1 = 4,
  O3_MINI = 5,
  GPT_4_1_MINI = 6,
  GPT_4_1_NANO = 7,
  GPT_4_1 = 8,
  O4_MINI = 9,
  O3 = 10,
  UNRECOGNIZED = -1,
}

export function openAIModelFromJSON(object: any): OpenAIModel {
  switch (object) {
    case 0:
    case "GPT_4O":
      return OpenAIModel.GPT_4O;
    case 1:
    case "GPT_3_5_TURBO":
      return OpenAIModel.GPT_3_5_TURBO;
    case 2:
    case "O1_MINI":
      return OpenAIModel.O1_MINI;
    case 3:
    case "O1_PREVIEW":
      return OpenAIModel.O1_PREVIEW;
    case 4:
    case "O1":
      return OpenAIModel.O1;
    case 5:
    case "O3_MINI":
      return OpenAIModel.O3_MINI;
    case 6:
    case "GPT_4_1_MINI":
      return OpenAIModel.GPT_4_1_MINI;
    case 7:
    case "GPT_4_1_NANO":
      return OpenAIModel.GPT_4_1_NANO;
    case 8:
    case "GPT_4_1":
      return OpenAIModel.GPT_4_1;
    case 9:
    case "O4_MINI":
      return OpenAIModel.O4_MINI;
    case 10:
    case "O3":
      return OpenAIModel.O3;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OpenAIModel.UNRECOGNIZED;
  }
}

export function openAIModelToJSON(object: OpenAIModel): string {
  switch (object) {
    case OpenAIModel.GPT_4O:
      return "GPT_4O";
    case OpenAIModel.GPT_3_5_TURBO:
      return "GPT_3_5_TURBO";
    case OpenAIModel.O1_MINI:
      return "O1_MINI";
    case OpenAIModel.O1_PREVIEW:
      return "O1_PREVIEW";
    case OpenAIModel.O1:
      return "O1";
    case OpenAIModel.O3_MINI:
      return "O3_MINI";
    case OpenAIModel.GPT_4_1_MINI:
      return "GPT_4_1_MINI";
    case OpenAIModel.GPT_4_1_NANO:
      return "GPT_4_1_NANO";
    case OpenAIModel.GPT_4_1:
      return "GPT_4_1";
    case OpenAIModel.O4_MINI:
      return "O4_MINI";
    case OpenAIModel.O3:
      return "O3";
    case OpenAIModel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum GroqModel {
  /** GROQ_LLAMA_4_SCOUT_17B_16E_INSTRUCT - Meta, 131K context, 8K completion */
  GROQ_LLAMA_4_SCOUT_17B_16E_INSTRUCT = 0,
  /** GROQ_LLAMA_4_MAVERICK_17B_128E_INSTRUCT - Meta, 131K context, 8K completion */
  GROQ_LLAMA_4_MAVERICK_17B_128E_INSTRUCT = 1,
  /** GROQ_DEEPSEEK_R1_DISTILL_LLAMA_70B - DeepSeek, 128K context */
  GROQ_DEEPSEEK_R1_DISTILL_LLAMA_70B = 2,
  /** GROQ_ALLAM_2_7B - SDAIA, 4K context */
  GROQ_ALLAM_2_7B = 3,
  /** GROQ_MISTRAL_SABA_24B - Mistral, 32K context */
  GROQ_MISTRAL_SABA_24B = 4,
  /** GROQ_QWEN_QWQ_32B - Alibaba Cloud, 128K context */
  GROQ_QWEN_QWQ_32B = 5,
  /** GROQ_PLAYAI_TTS - Playht, 10K context */
  GROQ_PLAYAI_TTS = 6,
  /** GROQ_PLAYAI_TTS_ARABIC - Playht, 10K context */
  GROQ_PLAYAI_TTS_ARABIC = 7,
  UNRECOGNIZED = -1,
}

export function groqModelFromJSON(object: any): GroqModel {
  switch (object) {
    case 0:
    case "GROQ_LLAMA_4_SCOUT_17B_16E_INSTRUCT":
      return GroqModel.GROQ_LLAMA_4_SCOUT_17B_16E_INSTRUCT;
    case 1:
    case "GROQ_LLAMA_4_MAVERICK_17B_128E_INSTRUCT":
      return GroqModel.GROQ_LLAMA_4_MAVERICK_17B_128E_INSTRUCT;
    case 2:
    case "GROQ_DEEPSEEK_R1_DISTILL_LLAMA_70B":
      return GroqModel.GROQ_DEEPSEEK_R1_DISTILL_LLAMA_70B;
    case 3:
    case "GROQ_ALLAM_2_7B":
      return GroqModel.GROQ_ALLAM_2_7B;
    case 4:
    case "GROQ_MISTRAL_SABA_24B":
      return GroqModel.GROQ_MISTRAL_SABA_24B;
    case 5:
    case "GROQ_QWEN_QWQ_32B":
      return GroqModel.GROQ_QWEN_QWQ_32B;
    case 6:
    case "GROQ_PLAYAI_TTS":
      return GroqModel.GROQ_PLAYAI_TTS;
    case 7:
    case "GROQ_PLAYAI_TTS_ARABIC":
      return GroqModel.GROQ_PLAYAI_TTS_ARABIC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GroqModel.UNRECOGNIZED;
  }
}

export function groqModelToJSON(object: GroqModel): string {
  switch (object) {
    case GroqModel.GROQ_LLAMA_4_SCOUT_17B_16E_INSTRUCT:
      return "GROQ_LLAMA_4_SCOUT_17B_16E_INSTRUCT";
    case GroqModel.GROQ_LLAMA_4_MAVERICK_17B_128E_INSTRUCT:
      return "GROQ_LLAMA_4_MAVERICK_17B_128E_INSTRUCT";
    case GroqModel.GROQ_DEEPSEEK_R1_DISTILL_LLAMA_70B:
      return "GROQ_DEEPSEEK_R1_DISTILL_LLAMA_70B";
    case GroqModel.GROQ_ALLAM_2_7B:
      return "GROQ_ALLAM_2_7B";
    case GroqModel.GROQ_MISTRAL_SABA_24B:
      return "GROQ_MISTRAL_SABA_24B";
    case GroqModel.GROQ_QWEN_QWQ_32B:
      return "GROQ_QWEN_QWQ_32B";
    case GroqModel.GROQ_PLAYAI_TTS:
      return "GROQ_PLAYAI_TTS";
    case GroqModel.GROQ_PLAYAI_TTS_ARABIC:
      return "GROQ_PLAYAI_TTS_ARABIC";
    case GroqModel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum MessageRole {
  MESSAGE_ROLE_USER = 0,
  MESSAGE_ROLE_SYSTEM = 1,
  MESSAGE_ROLE_ASSISTANT = 2,
  UNRECOGNIZED = -1,
}

export function messageRoleFromJSON(object: any): MessageRole {
  switch (object) {
    case 0:
    case "MESSAGE_ROLE_USER":
      return MessageRole.MESSAGE_ROLE_USER;
    case 1:
    case "MESSAGE_ROLE_SYSTEM":
      return MessageRole.MESSAGE_ROLE_SYSTEM;
    case 2:
    case "MESSAGE_ROLE_ASSISTANT":
      return MessageRole.MESSAGE_ROLE_ASSISTANT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageRole.UNRECOGNIZED;
  }
}

export function messageRoleToJSON(object: MessageRole): string {
  switch (object) {
    case MessageRole.MESSAGE_ROLE_USER:
      return "MESSAGE_ROLE_USER";
    case MessageRole.MESSAGE_ROLE_SYSTEM:
      return "MESSAGE_ROLE_SYSTEM";
    case MessageRole.MESSAGE_ROLE_ASSISTANT:
      return "MESSAGE_ROLE_ASSISTANT";
    case MessageRole.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Message {
  content: string;
  role: MessageRole;
  images: Uint8Array[];
  imageUrls: string[];
}

function createBaseMessage(): Message {
  return { content: "", role: 0, images: [], imageUrls: [] };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.role !== 0) {
      writer.uint32(16).int32(message.role);
    }
    for (const v of message.images) {
      writer.uint32(26).bytes(v!);
    }
    for (const v of message.imageUrls) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.images.push(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.imageUrls.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      role: isSet(object.role) ? messageRoleFromJSON(object.role) : 0,
      images: globalThis.Array.isArray(object?.images) ? object.images.map((e: any) => bytesFromBase64(e)) : [],
      imageUrls: globalThis.Array.isArray(object?.imageUrls)
        ? object.imageUrls.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.role !== 0) {
      obj.role = messageRoleToJSON(message.role);
    }
    if (message.images?.length) {
      obj.images = message.images.map((e) => base64FromBytes(e));
    }
    if (message.imageUrls?.length) {
      obj.imageUrls = message.imageUrls;
    }
    return obj;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
}
